# Generated by Django 6.1.1 on 2026-09-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signbank_id', models.IntegerField()),
                ('gloss_id', models.CharField(max_length=255)),
                ('old_video_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
