# Generated by Django 6.1.1 on 2026-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_appsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingitem',
            name='recording_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recordingitem',
            name='recording_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recordingitem',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recordingitem',
            name='signbank_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='recordingitem',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
