# Generated by Django 6.1.1 on 2026-09-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_recordingitem_recording_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingitem',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
