# Generated by Django 6.1.1 on 2026-09-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0004_alter_recordingitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingitem',
            name='review_status',
            field=models.CharField(blank=True, choices=[('goedgekeurd', 'Goedgekeurd'), ('afgekeurd', 'Afgekeurd'), ('overgeslagen', 'Overgeslagen')], default='', max_length=20),
        ),
    ]
