"""
Django settings for studio project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
import os
from pathlib import Path

ENV_FILE = "/home/vlaamseg/.vgt_studio_env"

if os.path.exists(ENV_FILE):
    with open(ENV_FILE) as f:
        for line in f:
            line = line.strip()

            if not line or line.startswith("#") or "=" not in line:
                continue

            key, value = line.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6*z-#eyw3o3k@h2xscfjy$_maznvfy(rd=rd7wrr6=rv#(c&zc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "studio.vlaamsegebarentaal.be",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",

    'recordings',
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "recordings.middleware.LoginRequiredMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'studio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'studio.wsgi.application'

CSRF_TRUSTED_ORIGINS = [

    "https://studio.vlaamsegebarentaal.be",

]


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },

    "postgres": {
        'ENGINE': "django.db.backends.postgresql",
        'NAME': "vlaamseg_vgtstudio",
        'USER': "vlaamseg_vgt_studio",
        'PASSWORD': "VGTc1997!",
        'HOST': "127.0.0.1",
        'PORT': "5432",
    },
}


# AUTHENTICATION GOOGLE
# google

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APPS": [
            {
                "client_id": os.environ.get("GOOGLE_OAUTH_CLIENT_ID"),
                "secret": os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET"),
                "key": "",
            }
        ],
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}

SOCIALACCOUNT_ADAPTER = "recordings.adapters.VGTStudioSocialAccountAdapter"

LOGIN_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/logged-out/"

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

SIGNBANK_GLOSSVIDEO_ROOT = "/home/vlaamseg/signbank/writable/glossvideo"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

SIGNBANK_BASE_URL = "https://vlaamsegebarentaal.be/signbank/"

WEBOPNAME_BASE_URL = "http://127.0.0.1:8000/"

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "recording_list"
WHITENOISE_STATIC_PREFIX = "/static/"

# Login/session 30 dagen bewaren

SESSION_COOKIE_AGE = 60 * 60 * 24 * 30

SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Alleen via HTTPS

SESSION_COOKIE_SECURE = True

CSRF_COOKIE_SECURE = True

# Nodig voor normale navigatie binnen de site

SESSION_COOKIE_SAMESITE = "Lax"

CSRF_COOKIE_SAMESITE = "Lax"

SESSION_COOKIE_PATH = "/"

CSRF_COOKIE_PATH = "/"

GOOGLE_SERVICE_ACCOUNT_FILE = (

    "/home/vlaamseg/private/google-service-account.json"

)

VGT_STUDIO_GOOGLE_ALLOWED_DOMAINS = [
    "vgtc.be",
]

SOCIALACCOUNT_ONLY = True
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_LOGIN_ON_GET = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

LOGGING = {

    "version": 1,

    "disable_existing_loggers": False,

    "handlers": {

        "vgt_studio_file": {

            "level": "ERROR",

            "class": "logging.FileHandler",

            "filename": "/home/vlaamseg/vgt-studio-error.log",

        },

    },

    "loggers": {

        "django": {

            "handlers": ["vgt_studio_file"],

            "level": "ERROR",

            "propagate": True,

        },

    },

}